######################################################################
# 국내TV 파일처리 설정파일 (Simple)
# 버전 : 1.0
######################################################################

  ######################################################################
  # 파일처리를 하기 전 처리

  전처리:
    삭제: # 정규식 매칭시 삭제. 단어나 확장자.  re.search(규칙) 사용
      - "nfo$"
      - "exe$"
      - "txt$"
      - "\\[예고\\]"
      
    
    이동:  # 정규식 매칭시 이동. 이동폴더는 foldername에서 설정 혹은 절대경로
      #av:
      #  - '^\\w+-\\d+\\.[\w\d]{3}$'

      test:
         - "conf$"

      # /data/mnt/토렌트/111:
      #  - "210312"

      # /data/영화:
      #  - 2160p
      #  - REMUX

    변환: # re.sub(소스, 타겟, 파일명) 실행
      
      # 월화드라마, 특별기획드라마, 제거
      - source : "^\\w{2,}드라마"
        target : ""

      # 설,추석 특집
      - source : "^\\w+\\s?특집"
        target : ""

      # Deresisi 릴 
      - source : "^(?P<title>(.*?))\\s(?P<all>E\\d+.*?Deresisi.*?mp4)$"
        target : "\\g<title>.\\g<all>"

      - source : "\\.최종회\\."
        target : "."

      - source : "\\.최종\\."
        target : "."

      - source : "\\.첫회\\."
        target : "."
      
      - source : "\\.첫방송\\."
        target : "."

      - source : "\\s\\d{7,}"
        target : ""

      - source : "써치"
        target : "진실을 검색하다, 써치"

