######################################################################
# 해외TV 파일처리 설정파일
# 버전 : 1.0
######################################################################


  ######################################################################
  # 이 값은  "다운로드 폴더처리"(기본처리)에서는 사용하지 않고, "설정파일을 사용하는 처리" 시에만 사용
  # 값을 모두 채우고 "설정파일을 사용하는 처리"에서 동작하면 기본처리와 동일.
  
- 소스 폴더 : 기본처리에는 DB 설정값 사용
  타겟 폴더 : 기본처리에는 DB 설정값 사용
  에러 폴더 : 기본처리에는 DB 설정값 사용
  타겟 폴더 구조 : 기본처리에는 DB 설정값 사용



  ######################################################################
  # 경로 설정
  # {error} : 에러 폴더 활용한 경로나 절대경로

  경로 설정:
    no_tv : "{error}/no_tv"       # tv 형식이 아닌 경우 (회차를 찾을 수 없을 때)
    no_meta : "{error}/no_meta"   # 메타 매칭이 실패할 경우 파일이 이동할 error 폴더내의 폴더명
    sub_x : "{error}/sub_x/{TITLE_FIRST_CHAR}/{TITLE} ({YEAR})/{SEASON}"  # 자막이 없을때 이동할 경로
    sub : "{error}/sub"
    test : "{error}/test"         # 이 외는 이동 폴더에 사용할 규칙


     
  ######################################################################
  # vod 분류: 영상에 한글자막이 입혀져 나오는 경우. 웨이브, 티빙은 더이상 한글자막이 입혀져 나오지 않는다.
  hard_subtitle: 
    - ".KOR."

  ######################################################################
  # 파일처리를 하기 전 처리

  전처리:
    파일삭제: # 정규식 매칭시 삭제. 단어나 확장자.  re.search(규칙) 사용
      - "nfo$"
      - "exe$"
      - "txt$"
      - "html$"
      - "torrent$"
      - "aria2__temp$"
    
    #폴더삭제: # 경로에 폴더이름이 있으면 삭제. 대소문자 구분
      #- 'Subs' #rarbg 자막파일들

    이동:  # 정규식 매칭시 이동. 이동폴더는 foldername에서 설정 혹은 절대경로
      test:
         - "conf$"

    변환: # re.sub(소스, 타겟, 파일명) 실행   
      - source : "의 사본$"
        target : ""
      - source : " 사본$"
        target : ""


  ######################################################################
  # 방송명 부분을 메타 탐색시 변경하여 검색
  # 전처리-변환 옵션은 파일명을 변경하지만 이 옵션은 파일명은 유지한채 검색시에만 사용
  # re.IGNORECASE 사용

  검색어 변경:
    # [] 안에 있는 문자 제거
    - source : "\\[.*?\\]"
      target : ""
    - source : ".US."
      target : ""
    - source : ".AU."
      target : ""
  ###################################################################### 
  # 리먹스같은 장르로 구별하기 힘든 것들 수동으로 지정하면 된다. 
#   타겟 수동 설정: 
#   - 이름: "타겟조건 리먹스"
#     타겟루트: "/mnt/gdrive/remux"
#     타겟포맷: "{TITLE_FIRST_CHAR}/{TITLE} ({YEAR})"
#     코드: |
#       def check(db_item):
#         if 'remux' in db_item.filename_original.lower() :
#           return True

  ###################################################################### 
  # 분리해서 추가할 시즌 설정
  # {SEASON} 에 적용된다. {season} 으로 할경우 사용하지 않는다.
  시즌 설정:
  - 이름: "시즌이름 UHD"
    시즌이름: "4K" # Season 101 시즌 1 뒤 이름
    시즌번호: "100" # Season 101, Season 102 형식이 된다.
    코드: |
      def check(db_item):
        if int(db_item.resolution.split('x')[0]) > 3000:
          return True
      
  
  - 이름: "시즌이름 더빙"
    시즌이름: "더빙"
    시즌번호: "200"
    코드: |
      def check(db_item):
        if db_item.include_kor_audio == True :
          return True

  # - 이름: "시즌이름 리먹스"
  #   시즌이름: "REMUX"
  #   시즌번호: "300"
  #   코드: |
  #     def check(db_item):
  #       if 'remux' in db_item.filename_original.lower() :
  #         return True

  ###################################################################### 
  장르 변경 규칙: 
    Kids: 키즈 
    애니메이션 : 애니메이션
    리얼리티 : 리얼리티
    다큐멘터리 : 다큐멘터리
    미국 : 미국드라마
    중국 : 중국드라마
    영국 : 영국드라마
    일본 : 일본드라마
    대만 : 대만드라마

  #PLEX_MATE_SCAN:
  #  - URL: "http://localhost:9999" #FF 주소
  #    경로변경:
  #      - 소스: "L:"
  #        타겟: "H:\\내 드라이브"
  #    #  - 소스:
  #    #    타켓:
